version: '3.6'

services:
  jupyter:
    image: rubydata/datascience-notebook
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./work:/home/jovyan/work:rw
